public class Main {
    public static <Var> void main(String[] args) { System.out.println("Домашняя Работа");
        System.out.println("Задача 1");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        System.out.println("Задача 3");
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = (frog + 10)/3.5;
        System.out.println(frog);
        System.out.println("Задача 6");
        var weightFirstboxer = 78.2;
        var weightSecondboxer = 82.7;
        var weightBoxers = weightFirstboxer + weightSecondboxer;
        System.out.println("Общий вес" + weightBoxers + "кг!");
        var differenceWeigth = weightSecondboxer - weightFirstboxer;
        System.out.println("Разница в весе" + differenceWeigth + "кг!");
        differenceWeigth = (weightSecondboxer% weightFirstboxer);
        System.out.println("Разницва в весе от деления" + differenceWeigth);
        System.out.println("Задача 7");
        var totalHours = 640;
        var workHours = 8;
        var people = totalHours/workHours;
        System.out.println("Всего работников в компании " + people + "человек");
        people = people + 94;
        System.out.println(people);
        workHours = totalHours/people;
        System.out.println("Если в компании работает"+people+"человек,"+"то всего"+workHours+"часов работы может быть поделено между сотрудниками");
    }}
